zdavatz/oddb.org

- src/plugin/bsv_xml.rb
- src/util/persistence.rb
> Add flags to packages with logic in RSS plugin

- test/test_plugin/bsv_xml.rb
Fixed test errors with bsv_xml
> Fixed test errors with bsv_xml

- src/plugin/bsv_xml.rb
> Fix issue with price not present when flag is calculated

- src/plugin/bsv_xml.rb
- src/util/updater.rb
#175 
Sie müssen noch einmal `import_bsv` laufen.
> Fix issue with package having nil pointer

- Gemfile
- src/custom/lookandfeelbase.rb
> Fix issue with showing form action url with port

- .github/workflows/ruby.yml
- Gemfile
- src/custom/lookandfeelbase.rb
- src/model/fachinfo.rb
- src/model/patinfo.rb
- src/plugin/text_info.rb
- test/test_view/ajax/ddd_chart.rb
incorporates the changes by brian, too
> Run tests with ruby 3.2.0 on github has failing tests, but runs

- src/view/rss/fachinfo.rb
- test/test_view/rss/fachinfo.rb
> Assign chapters to components in RSS

- src/plugin/swissmedic.rb
> Handle ODBAError

- src/plugin/atc_less.rb
- src/plugin/refdata.rb
> Try to handle ODBAError and wrong sax machine calls

- src/util/updater.rb
> Remove update_bsv from import_daily

- src/plugin/shortage.rb
> Update drug shortage scraping

- src/plugin/shortage.rb
- test/data/html/drugshortage-changed.html
- test/data/html/drugshortage.html
- test/test_plugin/shortage.rb
> Update test cases for #221

- .github/workflows/ruby.yml
- ext/fiparse/src/fiparse.rb
- ext/fiparse/src/textinfo_hpricot.rb
- src/plugin/text_info.rb
#234 #235  #236 
Sie müssen beide `fiparsed` und webserver (`rackup`) neuestarten, dann `reparse` noch einmal laufen
> Fix issue with image extraction

- .github/workflows/ruby.yml
- config.ru
- src/model/atcclass.rb
- test/test_model/atcclass.rb
Also cleaned up config.ru and removed test builds for ruby 3.0 and ruby 3.1
> Fix search result if seq.packages ist not a hash

- src/plugin/text_info.rb
- test/test_plugin/swissmedic.rb
- test/test_plugin/text_info.rb
- test/test_plugin/text_info_swissmedicinfo.rb
Also fixed a case where unit tests accessed the data directory, instead of the test/data
> Update etc/barcode_to_text_info.yml automatically

- ext/fiparse/src/fiparse.rb
- ext/fiparse/src/textinfo_hpricot.rb
- ext/fiparse/test/test_fachinfo_hpricot.rb
- src/plugin/text_info.rb
- src/state/admin/patinfo_pdf.rb
- test/test_plugin/text_info.rb
- test/test_plugin/text_info_swissmedicinfo.rb
Attention: fiparse daemon must be restarted after pulling!
> Re-add changes for importing images for FI/PI

- src/model/sequence.rb
> Handle expected data in database

- src/model/patinfo.rb
Add same_as? method in patinfo
> #287: Second Workaround for import_bsv

- devenv.lock
- devenv.nix
- devenv.yaml
- jobs/update_textinfo_swissmedicinfo
- src/model/registration.rb
- src/plugin/text_info.rb
Locally import_daily and import_bsv passed without any problem
> Fixes for reparse and import_bsv

- src/state/admin/sequence.rb
> Replace atc_class creation with create_atc_class
